#!/usr/bin/env node
// scripts/build-setup.js — compile the custom installer (installer/src/*.cs)
// into dist/Editor-Helper-Setup.exe using the bundled .NET Framework 4 csc.
// No .NET SDK needed — csc ships with Windows. C# 5 only.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'installer', 'src');
const OUT_DIR = path.join(ROOT, 'dist');
const OUT = path.join(OUT_DIR, 'Editor-Helper-Setup.exe');

const CSC = 'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\csc.exe';
const LIB = 'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\';

// Embed the brand avatar (Desktop/1.png) as a base64 PNG byte array into a
// generated, gitignored installer/src/_Assets.cs. The exe is self-contained —
// the avatar ships inside it, read as bytes here without ever viewing the
// image. Falls back to an empty array (→ the "EH" placeholder) if missing.
const AVATAR_PATH = 'C:\\Users\\dekixh\\Desktop\\1.png';
const ICON_PATH = path.join(ROOT, 'installer', 'icon.ico');

// Generate a Windows .ico from the avatar PNG so the exe carries it as its
// Explorer/taskbar icon. Uses PNG-in-ICO (one entry, the raw PNG wrapped in
// the ICONDIR/ICONDIRENTRY header) — supported by Vista+. No image viewing.
function genIcon() {
  let png;
  try { png = fs.readFileSync(AVATAR_PATH); }
  catch (e) { console.log('→ avatar png missing, no exe icon set'); return null; }
  let w = png.readUInt32BE(16), h = png.readUInt32BE(20);   // PNG IHDR
  const ico = Buffer.alloc(6 + 16 + png.length);
  ico.writeUInt16LE(0, 0);    // reserved
  ico.writeUInt16LE(1, 2);    // type = 1 (icon)
  ico.writeUInt16LE(1, 4);    // count = 1 entry
  ico[6] = w >= 256 ? 0 : w;  // width  (0 = 256)
  ico[7] = h >= 256 ? 0 : h;  // height (0 = 256)
  ico[8] = 0;                 // colors
  ico[9] = 0;                 // reserved
  ico.writeUInt16LE(1, 10);   // planes
  ico.writeUInt16LE(32, 12);  // bit count
  ico.writeUInt32LE(png.length, 14); // image size
  ico.writeUInt32LE(22, 18);  // offset to image data (6 + 16)
  png.copy(ico, 22);
  fs.writeFileSync(ICON_PATH, ico);
  console.log('→ generated exe icon: ' + w + 'x' + h + ' → ' + ICON_PATH);
  return ICON_PATH;
}

function genAssets() {
  let b64 = '';
  try { b64 = fs.readFileSync(AVATAR_PATH).toString('base64'); }
  catch (e) { console.log('→ avatar not found at ' + AVATAR_PATH + ' (placeholder used)'); }
  const chunks = [];
  for (let i = 0; i < b64.length; i += 1000) chunks.push(b64.slice(i, i + 1000));
  const lit = chunks.map((c) => '"' + c + '"').join(' +\n            ');
  const src =
'// AUTO-GENERATED by scripts/build-setup.js — brand avatar embedded as a PNG\n' +
'// byte array. Do not edit by hand; gitignored (not committed).\n' +
'using System;\n' +
'namespace EhSetup\n' +
'{\n' +
'    internal static class Assets\n' +
'    {\n' +
'        public static readonly byte[] AvatarPng = Convert.FromBase64String(\n' +
'            ' + (lit.length ? lit : '""') + ');\n' +
'    }\n' +
'}\n';
  fs.writeFileSync(path.join(SRC_DIR, '_Assets.cs'), src);
  console.log('→ embedded avatar: ' + (b64.length ? (b64.length / 1024).toFixed(0) + ' KB (b64)' : 'none'));
}

function main() {
  if (!fs.existsSync(CSC)) throw new Error('csc not found: ' + CSC);
  if (!fs.existsSync(SRC_DIR)) throw new Error('src dir not found: ' + SRC_DIR);
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  genAssets();
  const icon = genIcon();

  const sources = fs.readdirSync(SRC_DIR).filter((f) => f.endsWith('.cs'))
    .map((f) => '"' + path.join(SRC_DIR, f) + '"');
  if (!sources.length) throw new Error('no .cs files in ' + SRC_DIR);

  const refs = ['System.dll', 'System.Windows.Forms.dll', 'System.Drawing.dll']
    .map((a) => '/reference:"' + LIB + a + '"');

  const args = [
    '/nologo', '/noconfig',
    '/target:winexe', '/platform:anycpu',
    '/utf8output',
    '/out:"' + OUT + '"',
  ];
  if (icon) args.push('/win32icon:"' + icon + '"');
  args.push(...refs, ...sources);

  console.log('→ compiling installer (' + sources.length + ' files)…');
  execSync('"' + CSC + '" ' + args.join(' '), { stdio: 'inherit', shell: true });
  if (!fs.existsSync(OUT)) throw new Error('build produced no exe: ' + OUT);
  console.log('✓ ' + OUT + '  (' + (fs.statSync(OUT).size / 1024).toFixed(0) + ' KB)');
}

try { main(); } catch (e) { console.error('✗', e.message); process.exit(1); }